name = "ip-check"
main = "worker.js"
# Set this to today's date
compatibility_date = "2026-05-23"
compatibility_flags = [ "nodejs_compat" ]

# [assets]
# binding = "ASSETS"
# directory = "dist"

[observability]
enabled = true
